//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pic_Vid
    {
        public int Unique_Id { get; set; }
        public string Name { get; set; }
        public string Full_Path { get; set; }
        public string Type { get; set; }
        public double Size { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Modified { get; set; }
        public string Values { get; set; }
    }
}
